Repository fga-gpp-mds/2018.1-Lacos-da-Alegria, pull requests merged in 2018-06, with the labels that each got.

#212 Added results of sprint 07
  docs/sprints/sprint07/images/burndown_sprint7.png
  docs/sprints/sprint07/images/knowledge_framework_sprint7.png
  docs/sprints/sprint07/images/results_sprint7.png
  docs/sprints/sprint07/images/retrospective_sprint7.png
  docs/sprints/sprint07/images/timetable_sprint7.png
  docs/sprints/sprint07/images/velocity_sprint7.png
  docs/sprints/sprint07/results.md
Labels: EPS, Scrum Master, easy, management

#211 Added results of sprint 09.
  docs/sprints/sprint09/images/burndown_sprint9.png
  docs/sprints/sprint09/images/commits_frontend_sprint9.png
  docs/sprints/sprint09/images/knowledge_framework_sprint9.png
  docs/sprints/sprint09/images/results_sprint9.png
  docs/sprints/sprint09/images/retrospective_sprint9.png
  docs/sprints/sprint09/images/timetable_sprint9.png
  docs/sprints/sprint09/images/velocity_sprint9.png
  docs/sprints/sprint09/results.md
Labels: EPS, Scrum Master, documentation, easy, management

#215 Acceptance tests
  package.json
  src/acceptanceTestFunctions/testFunctions.ts
  src/pages/about/about.e2e.spec.ts
  src/pages/activity-details/activity-details.e2e.spec.ts
  src/pages/help/help.e2e.spec.ts
  src/pages/list-activity/list-activity.e2e.spec.ts
  src/pages/login/login.e2e.spec.ts
  src/pages/menu-app/menu-app.e2e.spec.ts
  src/pages/news/news.e2e.spec.ts
  src/pages/profile/profile.e2e.spec.ts
  src/pages/register/register.e2e.spec.ts
  src/pages/settings/settings.e2e.spec.ts
  src/pages/tabs/tabs.e2e.spec.ts
  src/pages/welcome/welcome.e2e.spec.ts
Labels: architect, development team, frontend, important, tecnical story, test

#226 Implemented permission restriction
  src/app/app.component.ts
  src/app/app.module.ts
  src/models/user.ts
  src/pages/activities-list/activities-list.html
  src/pages/activities-list/activities-list.ts
  src/pages/activity-details/activity-details.ts
  src/pages/login/login.ts
  src/pages/menu-app/menu-app.html
  src/pages/menu-app/menu-app.ts
  src/pages/profile/profile.ts
  src/pages/register/register.ts
  src/pages/tabs/tabs.ts
  src/providers/rest-user.ts
  src/providers/role.service.ts
Labels: frontend, medium, review, user story

#238 Refactored CSS in pages before the login
  src/pages/login/login.html
  src/pages/login/login.scss
  src/pages/login/login.ts
  src/pages/register/register.html
  src/pages/register/register.scss
  src/pages/welcome/welcome.html
  src/pages/welcome/welcome.scss
Labels: development team, frontend

#240 Added delete user function
  src/pages/profile/profile.html
  src/pages/profile/profile.ts
  src/providers/rest-user.ts
Labels: backend, development team, frontend, medium

#235 Added planning of Sprint 12.
  docs/sprints/sprint12/images/burndown_risk_sprint12.png
  docs/sprints/sprint12/images/pairing_table_sprint12.png
  docs/sprints/sprint12/planning.md
Labels: Boas práticas, EPS, Scrum Master, documentation, easy, management

#229 Update results of Sprint 02
  docs/sprints/sprint02/results.md
Labels: EPS, bug, documentation, management

#252 Adicionado resultados da sprint 12.
  docs/sprints/sprint12/images/burndown_sprint12.png
  docs/sprints/sprint12/images/knowledge_framework_sprint12.png
  docs/sprints/sprint12/images/metrics_backend_sprint12.png
  docs/sprints/sprint12/images/results_sprint12.png
  docs/sprints/sprint12/images/retrospective_sprint12.png
  docs/sprints/sprint12/images/timetable_sprint12.png
  docs/sprints/sprint12/images/velocity_sprint12.png
  docs/sprints/sprint12/results.md
Labels: Boas práticas, EPS, Scrum Master, documentation, easy, management

#250 Added planning of sprint 13.
  docs/sprints/sprint13/images/burndown_risk_sprint13.png
  docs/sprints/sprint13/images/pairing_table_sprint13.png
  docs/sprints/sprint13/planning.md
Labels: Boas práticas, EPS, Scrum Master, documentation, easy, management

#253 Refactored CSS in pages after the login
  src/pages/activities-list/activities-list.html
  src/pages/activities-list/activities-list.scss
  src/pages/activities-list/activities-list.ts
  src/pages/activity-details/activity-details.html
  src/pages/activity-details/activity-details.scss
  src/pages/activity-details/activity-details.ts
  src/pages/profile/profile.html
  src/pages/profile/profile.scss
  src/pages/profile/profile.ts
  src/theme/variables.scss
Labels: frontend, medium, review, technical debt

#255 Feature/#216 subscription activity
  package-lock.json
  package.json
  src/acceptanceTestFunctions/testFunctions.ts
  src/pages/about/about.e2e.spec.ts
  src/pages/activities-list/activities-list.e2e.spec.ts
  src/pages/activities-list/activities-list.ts
  src/pages/activity-details/activity-details.e2e.spec.ts
  src/pages/activity-details/activity-details.html
  src/pages/activity-details/activity-details.ts
  src/pages/help/help.e2e.spec.ts
  src/pages/list-activity/list-activity.e2e.spec.ts
  src/pages/login/login.e2e.spec.ts
  src/pages/login/login.ts
  src/pages/menu-app/menu-app.e2e.spec.ts
  src/pages/news/news.e2e.spec.ts
  src/pages/profile/profile.e2e.spec.ts
  src/pages/register/register.e2e.spec.ts
  src/pages/register/register.ts
  src/pages/settings/settings.e2e.spec.ts
  src/pages/tabs/tabs.e2e.spec.ts
  src/pages/tabs/tabs.ts
  src/pages/welcome/welcome.e2e.spec.ts
  src/providers/rest-activity.ts
  src/providers/rest-user.ts
  src/providers/storage.service.ts
Labels: development team, technical debt, test

#268 Added user profile photo
  config.xml
  package-lock.json
  package.json
  src/app/app.module.ts
  src/models/user.ts
  src/pages/profile/profile.html
  src/pages/profile/profile.scss
  src/pages/profile/profile.ts
  src/pages/register/register.ts
  src/providers/rest-activity.ts
  src/providers/rest-user.ts
  src/providers/storage.service.ts
Labels: development team, frontend

#269 Added results of Sprint 13.
  docs/sprints/sprint13/images/burndown_sprint13.png
  docs/sprints/sprint13/images/commits_backend.png
  docs/sprints/sprint13/images/commits_frontend.png
  docs/sprints/sprint13/images/knowledge_framework_sprint13.png
  docs/sprints/sprint13/images/metrics_backend_sprint13.png
  docs/sprints/sprint13/images/results_sprint13.png
  docs/sprints/sprint13/images/retrospective_sprint13.png
  docs/sprints/sprint13/images/timetable_sprint13.png
  docs/sprints/sprint13/images/velocity_sprint13.png
  docs/sprints/sprint13/results.md
Labels: Boas práticas, EPS, Scrum Master, documentation, easy, management

#276 Improved Comments
  src/app/app.component.ts
  src/app/app.module.ts
  src/pages/activities-list/activities-list.e2e.spec.ts
  src/pages/activities-list/activities-list.scss
  src/pages/activities-list/activities-list.spec.ts
  src/pages/activities-list/activities-list.ts
  src/pages/activity-details/activity-details.e2e.spec.ts
  src/pages/activity-details/activity-details.html
  src/pages/activity-details/activity-details.spec.ts
  src/pages/activity-details/activity-details.ts
  src/pages/help/help.e2e.spec.ts
  src/pages/help/help.scss
  src/pages/list-activity/list-activity.e2e.spec.ts
  src/pages/list-activity/list-activity.html
  src/pages/list-activity/list-activity.scss
  src/pages/list-activity/list-activity.ts
  src/pages/listuser/listuser.html
  src/pages/listuser/listuser.scss
  src/pages/listuser/listuser.ts
  src/pages/login/login.e2e.spec.ts
  src/pages/login/login.html
  src/pages/login/login.scss
  src/pages/login/login.ts
  src/pages/menu-app/menu-app.e2e.spec.ts
  src/pages/menu-app/menu-app.html
  src/pages/menu-app/menu-app.ts
  src/pages/news/news.e2e.spec.ts
  src/pages/news/news.html
  src/pages/news/news.scss
  src/pages/news/news.ts
  src/pages/profile/profile.e2e.spec.ts
  src/pages/profile/profile.html
  src/pages/profile/profile.scss
  src/pages/profile/profile.ts
  src/pages/register/register.e2e.spec.ts
  src/pages/register/register.scss
  src/pages/register/register.spec.ts
  src/pages/register/register.ts
  src/pages/settings/settings.e2e.spec.ts
  src/pages/settings/settings.html
  src/pages/settings/settings.scss
  src/pages/settings/settings.ts
  src/pages/tabs/tabs.e2e.spec.ts
  src/pages/tabs/tabs.html
  src/pages/tabs/tabs.ts
  src/pages/welcome/welcome.e2e.spec.ts
  src/providers/rest-activity.ts
  src/providers/rest-news.ts
  src/providers/rest-user.ts
  src/validators/cpf-validation.ts
  src/validators/email-validation.ts
Labels: easy, frontend

#272 Evm
  docs/sprints/sprint08/results.md
  docs/sprints/sprint09/results.md
  docs/sprints/sprint10/results.md
  docs/sprints/sprint11/results.md
  docs/sprints/sprint12/results.md
Labels: Boas práticas, PO, documentation

#282 Updated class diagram.
  docs/images/diagrama_de_classes.png
Labels: documentation

#280 Added results of sprint 14.
  docs/sprints/sprint14/images/burndown_sprint14.png
  docs/sprints/sprint14/images/commits_backend.png
  docs/sprints/sprint14/images/commits_frontend.png
  docs/sprints/sprint14/images/knowledge_framework_sprint14.png
  docs/sprints/sprint14/images/metrics_backend_sprint14.png
  docs/sprints/sprint14/images/results_sprint14.png
  docs/sprints/sprint14/images/retrospective_sprint14.png
  docs/sprints/sprint14/images/timetable_sprint14.png
  docs/sprints/sprint14/images/velocity_sprint14.png
  docs/sprints/sprint14/results.md
Labels: Boas práticas, EPS, Scrum Master, documentation, easy, management
