Repository fga-gpp-mds/2018.1-Lacos-da-Alegria, pull requests merged in 2018-05, with the labels that each got.

#145 Added planning of sprint 06.
  docs/sprints/sprint06/images/burndown_risk_sprint6.png
  docs/sprints/sprint06/images/pairing_table_sprint06.png
  docs/sprints/sprint06/planning.md
Labels: EPS, Scrum Master, documentation, easy, management

#144 Added results of sprint 05.
  docs/sprints/sprint05/images/burndown_sprint5.png
  docs/sprints/sprint05/images/commits_backend_sprint5.png
  docs/sprints/sprint05/images/commits_frontend_sprint5.png
  docs/sprints/sprint05/images/knowledge_framework_sprint5.png
  docs/sprints/sprint05/images/results_sprint5.png
  docs/sprints/sprint05/images/retrospective_sprint5.png
  docs/sprints/sprint05/images/timetable_sprint5.png
  docs/sprints/sprint05/images/velocity_sprint5.png
  docs/sprints/sprint05/results.md
Labels: EPS, Scrum Master, documentation, easy, management

#177 Refactored prototype
  docs/evolve_prototype.md
  docs/images/tela_de_atividades.png
  docs/images/tela_de_cadastro.png
  docs/images/tela_de_lista.png
  docs/images/tela_de_login.png
  docs/images/tela_de_menu.png
  docs/images/tela_de_novidades.png
  docs/images/tela_de_perfil.png
  docs/images/tela_inicial.png
Labels: development team, documentation, refactor

#172 Feature/#170 solve bugs
  src/app/app.component.ts
  src/pages/activities-list/activities-list.html
  src/pages/create-activity/create-activity.html
  src/pages/create-activity/create-activity.scss
  src/pages/create-activity/create-activity.ts
  src/pages/login/login.ts
  src/pages/register/register.ts
  src/pages/welcome/welcome.ts
Labels: bug, development team, easy, frontend

#187 Added user login and logout
  src/app/app.module.ts
  src/models/local-user.ts
  src/models/refresh-token.ts
  src/pages/home/home.ts
  src/pages/login/login.spec.ts
  src/pages/login/login.ts
  src/pages/welcome/welcome.ts
  src/providers/rest/rest.ts
  src/providers/storage.service.ts
Labels: frontend, important, medium, technical debt, test, user story

#188 User Profile
  src/app/app.module.ts
  src/pages/activities-list/activities-list.ts
  src/pages/activity-details/activity-details.ts
  src/pages/home/home.ts
  src/pages/listuser/listuser.ts
  src/pages/login/login.spec.ts
  src/pages/login/login.ts
  src/pages/profile/profile.html
  src/pages/profile/profile.spec.ts
  src/pages/profile/profile.ts
  src/pages/register/register.spec.ts
  src/pages/register/register.ts
  src/pages/welcome/welcome.ts
  src/providers/rest-activity.ts
  src/providers/rest-user.ts
Labels: frontend

#191 Created slide based 'WelcomePage'.
  src/pages/welcome/welcome.html
  src/pages/welcome/welcome.scss
  src/pages/welcome/welcome.ts
Labels: development team, frontend, help me, medium, review

#189 Test activities front
  src/app/app.module.ts
  src/pages/activities-list/activities-list.spec.ts
  src/pages/activity-details/activity-details.spec.ts
  src/pages/activity-details/activity-details.ts
Labels: frontend

#173 Results of sprint 06
  docs/sprints/sprint06/images/burndown_sprint6.png
  docs/sprints/sprint06/images/commits_frontend_sprint6.png
  docs/sprints/sprint06/images/knowledge_framework_sprint6.png
  docs/sprints/sprint06/images/results_sprint6.png
  docs/sprints/sprint06/images/retrospective_sprint6.png
  docs/sprints/sprint06/images/timetable_sprint6.png
  docs/sprints/sprint06/images/velocity_sprint6.png
  docs/sprints/sprint06/results.md
Labels: EPS, Scrum Master, documentation, easy, management

#198 Added planning of sprint 09.
  docs/sprints/sprint09/images/burndown_risk_sprint9.png
  docs/sprints/sprint09/images/pairing_table_sprint09.png
  docs/sprints/sprint09/planning.md
Labels: EPS, Scrum Master, documentation, easy

#199 Added acceptance tests config.
  e2e/tsconfig.json
  src/pages/login/login.e2e.spec.ts
  test-config/protractor.conf.js
Labels: EPS, configure, devops, documentation, easy, tecnical story

#202 Refactor user's functionalities
  src/app/app.module.ts
  src/models/user.ts
  src/pages/login/login.html
  src/pages/login/login.ts
  src/pages/menuApp/menuApp.html
  src/pages/menuApp/menuApp.ts
  src/pages/profile/profile.html
  src/pages/profile/profile.ts
  src/pages/register/register.html
  src/pages/register/register.ts
  src/pages/tabs/tabs.ts
  src/validators/cpf-validation.ts
  src/validators/email-validation.ts
Labels: development team, frontend, important, refactor

#206 Refactored user's functionalities
  docs/style_guide.md
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/pages/activities-list/activities-list.ts
  src/pages/activity-details/activity-details.ts
  src/pages/listuser/listuser.ts
  src/pages/login/login.scss
  src/pages/login/login.ts
  src/pages/menu-app/menu-app.html
  src/pages/menu-app/menu-app.scss
  src/pages/menu-app/menu-app.ts
  src/pages/register/register.html
  src/pages/register/register.scss
  src/pages/register/register.ts
  src/pages/tabs/tabs.ts
  src/pages/welcome/welcome.ts
  src/providers/rest-user.ts
  src/providers/storage.service.ts
  src/theme/variables.scss
Labels: bug, development team, frontend, important, refactor, review

#182 Added planning of sprint 08.
  docs/sprints/sprint08/images/burndown_risk_sprint8.png
  docs/sprints/sprint08/images/pairing_table_sprint08.png
  docs/sprints/sprint08/planning.md
Labels: EPS, Scrum Master, documentation, easy, management

#209 Added planning of Sprint 10.
  docs/sprints/sprint10/images/burndown_risk_sprint10.png
  docs/sprints/sprint10/images/pairing_table_sprint10.png
  docs/sprints/sprint10/planning.md
Labels: EPS, Scrum Master, documentation, easy

#210 Added results of sprint 08.
  docs/sprints/sprint08/images/burndown_sprint8.png
  docs/sprints/sprint08/images/knowledge_framework_sprint8.png
  docs/sprints/sprint08/images/results_sprint8.png
  docs/sprints/sprint08/images/retrospective_sprint8.png
  docs/sprints/sprint08/images/timetable_sprint8.png
  docs/sprints/sprint08/images/velocity_sprint8.png
  docs/sprints/sprint08/results.md
Labels: EPS, Scrum Master, documentation, management
