Repository fga-gpp-mds/2018.1-Lacos-da-Alegria, pull requests merged in 2018-03, with the labels that each got.

#28 Fixed path of images.
  docs/images/roles_methodology.png
  docs/methodology_document.md
Labels: invalid

#57 Supplementary specification completed
  docs/supplementary_specification.md
Labels: MDS, documentation, review

#56 Style Guide completed.
  docs/style_guide.md
Labels: MDS, bug, documentation, review

#30 Vision Document completed
  docs/vision_document.md
Labels: MDS, documentation, review

#29 Architecture document completed.
  docs/architecture_document.md
  docs/images/classDiagram.png
  docs/images/cordova.jpg
Labels: MDS, architecture, documentation, review
