Repository fga-gpp-mds/2018.1-Lacos-da-Alegria, pull requests merged in 2018-04, with the labels that each got.

#73 Corrected erros from the previous review.
  docs/style_guide.md
Labels: MDS, documentation, easy, review

#79 Added change history and summary.
  docs/architecture_document.md
Labels: MDS, architecture, documentation, important, review

#83 Created prototype_document
  Dockerfile
  LICENSE
  README.md
  config.xml
  docker-compose.yml
  docs/evolve_prototype.md
  docs/images/tela_de_atividades.png
  docs/images/tela_de_lista.png
  docs/images/tela_de_login.png
  docs/images/tela_de_menu.png
  docs/images/tela_de_novidades.png
  docs/images/tela_de_perfil.png
  docs/images/tela_inicial.png
  ionic.config.json
  package-lock.json
  package.json
  spec/support/jasmine.json
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/app.html
  src/app/app.module.ts
  src/index.html
  src/pages/about/about.html
  src/pages/about/about.scss
  src/pages/about/about.ts
  src/pages/contact/contact.html
  src/pages/contact/contact.scss
  src/pages/contact/contact.ts
  src/pages/home/home.html
  src/pages/list/list.html
  src/pages/list/list.scss
  src/pages/list/list.ts
  src/pages/login/login.spec.ts
  src/pages/tabs/tabs.html
  src/pages/tabs/tabs.ts
  tsconfig.json
Labels: MDS, documentation, important, review

#43 Added results of Sprint 1 and planning of Sprint 2
  docs/sprints/images/burndown_risk_sprint2.png
  docs/sprints/images/burndown_sprint1.png
  docs/sprints/images/commits_sprint1.png
  docs/sprints/images/knowledge_framework_sprint1.png
  docs/sprints/images/pairing_table_sprint02.png
  docs/sprints/images/results_sprint1.png
  docs/sprints/images/retrospective_sprint1.png
  docs/sprints/images/timetable_sprint1.png
  docs/sprints/images/velocity_sprint1.png
  docs/sprints/sprint01/planning.md
  docs/sprints/sprint01/results.md
  docs/sprints/sprint02/planning.md
Labels: EPS, documentation, management

#68 Added meeting recording document
  AtaReinao.md
  AtaTreinamento.md
  docs/AtaReinao.md
  docs/AtaTreinamento.md
  images/eap.jpg
  images/roadmap_architecture.png
  images/roadmap_architecture2.png
  images/roadmap_projeto.png
Labels: Boas práticas, documentation, refactor

#69 Added pull request template.
  docs/pull_request_template.md
Labels: Boas práticas, documentation, easy, important

#70 Added issue template.
  docs/issue_template.md
Labels: Boas práticas, EPS, documentation, easy, important, review

#80 Refactored methodology document.
  docs/methodology_document.md
Labels: EPS, documentation, easy, management, refactor

#81 Added results of sprint 2.
  docs/sprints/images/burndown_sprint2.png
  docs/sprints/images/commits_sprint2.png
  docs/sprints/images/knowledge_framework_sprint2.png
  docs/sprints/images/results_sprint2.png
  docs/sprints/images/retrospective_sprint2.png
  docs/sprints/images/timetable_sprint2.png
  docs/sprints/images/velocity_sprint2.png
  docs/sprints/sprint02/results.md
Labels: EPS, documentation, easy, management

#104 Added planning of Sprint 04.
  docs/sprints/images/burndown_risk_sprint4.png
  docs/sprints/images/pairing_table_sprint04.png
  docs/sprints/sprint04/planning.md
Labels: EPS, Scrum Master, documentation, easy, review

#120 Feature/#101 create users
  src/pages/register/register.html
  src/pages/register/register.ts
  src/providers/rest/rest.ts
Labels: development team, frontend, important, medium, review

#122 Added planning of sprint 5.
  docs/sprints/images/burndown_risk_sprint5.png
  docs/sprints/images/pairing_table_sprint05.png
  docs/sprints/sprint05/planning.md
Labels: EPS, Scrum Master, documentation, easy, management

#121 Added results of sprint3
  docs/sprints/images/burndown_sprint3.png
  docs/sprints/images/commits_frontend_sprint3.png
  docs/sprints/images/knowledge_framework_sprint3.png
  docs/sprints/images/results_sprint3.png
  docs/sprints/images/retrospective_sprint3.png
  docs/sprints/images/timetable_sprint3.png
  docs/sprints/images/velocity_sprint3.png
  docs/sprints/sprint03/results.md
Labels: EPS, Scrum Master, documentation, easy, management

#124 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: Boas práticas, EPS, documentation

#133 Created app skeleton - Frontend
  src/app/app.component.ts
  src/app/app.module.ts
  src/pages/about/about.html
  src/pages/about/about.module.ts
  src/pages/about/about.scss
  src/pages/about/about.ts
  src/pages/activities-list/activities-list.html
  src/pages/activities-list/activities-list.scss
  src/pages/create-activity/create-activity.html
  src/pages/create-activity/create-activity.ts
  src/pages/profile/profile.html
  src/pages/profile/profile.scss
  src/pages/profile/profile.ts
  src/pages/settings/settings.html
  src/pages/settings/settings.module.ts
  src/pages/settings/settings.scss
  src/pages/settings/settings.ts
  src/providers/rest-api/rest-api.ts
Labels: development team, frontend, review

#129 Added results of Sprint 04.
  docs/sprints/images/commits_sprint4.png
  docs/sprints/sprint04/images/burndown_risk_sprint4.png
  docs/sprints/sprint04/images/burndown_sprint4.png
  docs/sprints/sprint04/images/commits_frontend_sprint4.png
  docs/sprints/sprint04/images/knowledge_framework_sprint4.png
  docs/sprints/sprint04/images/results_sprint4.png
  docs/sprints/sprint04/images/retrospective_sprint4.png
  docs/sprints/sprint04/images/timetable_sprint4.png
  docs/sprints/sprint04/images/velocity_sprint4.png
  docs/sprints/sprint04/results.md
Labels: EPS, Scrum Master, documentation, easy, management

#131 Feature/#114 user login
  src/pages/home/home.html
  src/pages/home/home.ts
  src/pages/login/login.html
  src/pages/login/login.ts
  src/pages/register/register.html
  src/pages/register/register.ts
  src/providers/rest/rest.ts
Labels: frontend, important, medium

#132 Added branches policy
  docs/branch_policy.md
  docs/images/branchs_policy.png
Labels: EPS, Scrum Master, documentation, easy

#135 Feature/#117 activities details
  src/app/app.component.ts
  src/app/app.module.ts
  src/pages/activities-list/activities-list.html
  src/pages/activities-list/activities-list.ts
  src/pages/activity-details/activity-details.html
  src/pages/activity-details/activity-details.scss
  src/pages/activity-details/activity-details.ts
  src/pages/list/list.html
  src/pages/list/list.scss
  src/pages/list/list.ts
  src/pages/listuser/listuser.html
  src/pages/register/register.ts
  src/providers/rest-api/rest-api.ts
Labels: development team, review, test

#137 Refactored architecture document
  docs/architecture_document.md
  docs/images/arquitetura_ionic.png
  docs/images/arquitetura_projeto.png
  docs/images/diagrama_de_classes.png
  docs/images/diagrama_de_pacotes.png
Labels: architecture, development team, documentation, important, refactor

#123 Criar Roadmap
  docs/roadmap.md
Labels: Scrum Master, architecture, devops, documentation, technical debt
